INSERT INTO mapfood.restaurant_type (name) VALUES ('Lanches');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Saudável');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Variada');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Brasileira');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Pizza');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Sorvetes');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Italiana');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Frutos Do Mar');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Mexicana');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Japonesa');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Indiana');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Árabe');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Carnes');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Cozinha Rápida');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Bebidas');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Vegetariana           ');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Chinesa');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Mediterrânea');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Doces & Bolos');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Portuguesa');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Contemporânea');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Alemã');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Salgados');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Francesa');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Açaí');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Marmita');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Asiática');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Peruana');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Comida Tailandesa');
INSERT INTO mapfood.restaurant_type (name) VALUES ('Doces E Salgados      ');
